---
- name: network interface information and ip address and hostname
  hosts: prod
  tasks: 
    - name: network interface information
      debug:
        msg: "{{ansible_facts['default_ipv4']['interface']}}"
    
    - name: ip address
      debug:
        msg: "{{ansible_facts['default_ipv4']['address']}}"

    - name: hostname
      debug:
        msg: "{{ansible_facts['hostname']}}"
